import { test, expect } from '@playwright/test';
test('reviewer sees evidence, records decisions and publishes from the separate console', async ({ page }) => {
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByText('Synthetic demonstration', { exact: false })).toBeVisible();
  await expect(page.getByText('Status: unreviewed', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Approve', exact: true }).first().click();
  await expect(page.getByRole('status')).toHaveText('Enter a reason for this decision.');
  await page.getByText('Source and reviewed reasoning', { exact: true }).first().click();
  await expect(page.getByRole('heading', { name: 'Synthetic escalation policy' }).first()).toBeVisible();
  await page.getByLabel('Legal review reason', { exact: true }).fill('Synthetic browser review.');
  await page.getByRole('button', { name: 'Approve', exact: true }).first().click();
  await expect(page.getByText('Status: awaiting owner review', { exact: false })).toBeVisible();
  for (let index = 0; index < 2; index++) {
    const card = page.getByRole('article').nth(index);
    await card.getByLabel('Recorded owner’s reason').fill('Synthetic owner consent.');
    await card.getByRole('button', { name: 'Approve', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('Up to date.');
  }
  await expect(page.getByText('Status: approved', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Publish to synthetic store' }).first().click();
  await expect(page.getByText('Status: partially published', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Publish to synthetic store' }).click();
  await expect(page.getByText('Status: published ·', { exact: false })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
test('author selects evidence, obtains assessment approval and prepares a change set', async ({ page }) => {
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Assess document evidence' }).click();
  await expect(page.getByRole('heading', { name: 'Assess document evidence' })).toBeVisible();
  await page.getByLabel('Document', { exact: true }).selectOption({ label: 'Synthetic authoring template · demo-matter · v1' });
  await page.getByRole('button', { name: 'Load evidence' }).click();
  await expect(page.getByLabel('Document text')).toHaveValue('Notify the incident owner.');
  await page.getByRole('button', { name: 'Use full segment' }).click();
  await page.getByLabel('Assessment rationale', { exact: true }).fill('Synthetic evidence supports a revised acknowledgement step.');
  await page.getByLabel('Application to this document', { exact: true }).fill('Synthetic template and rule only.');
  await page.getByLabel('I have confirmed the relevant context is complete').check();
  await page.getByRole('button', { name: 'Save assessment for review' }).click();
  await expect(page.getByText('Assessment status: unreviewed', { exact: false })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Create change set' })).toHaveCount(0);
  await page.getByLabel('Assessment review reason').fill('Reviewed synthetic source, passage and application.');
  await page.getByRole('button', { name: 'Approve assessment' }).click();
  await expect(page.getByText('Assessment status: approved', { exact: false })).toBeVisible();
  await page.getByLabel('Replacement wording').fill('Notify the incident owner and record acknowledgement.');
  await page.getByLabel('Change-set title').fill('Browser-authored maintenance');
  await page.getByLabel('Change-set rationale').fill('Propagate the reviewed synthetic requirement.');
  await page.getByLabel('Review expiry').fill('2099-01-01T12:00');
  await page.getByRole('button', { name: 'Create change set' }).click();
  await expect(page.getByRole('heading', { name: 'Browser-authored maintenance' })).toBeVisible();
  await expect(page.getByText('Status: unreviewed ·', { exact: false })).toBeVisible();
  await expect(page.getByText('Notify the incident owner and record acknowledgement.', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
